server:
  port: 8080

spring:
  application:
    name: payflow-api
  profiles:
    active: local
  modulith:
    events:
      republish-outstanding-events-on-restart: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{requestId:-}] %-5level %logger{36} - %msg%n"

payflow:
  idempotency:
    ttl-hours: 24
    cleanup-cron: "0 0 * * * *"
