apiVersion: v1
kind: ConfigMap
metadata:
  name: payflow-config
  labels:
    app.kubernetes.io/name: payflow-api
    app.kubernetes.io/part-of: payflow-platform
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/payflow_db"
  SPRING_DATASOURCE_USERNAME: "payflow"
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SPRING_AI_OLLAMA_BASE_URL: "http://ollama-service:11434"
  PAYFLOW_CORS_ALLOWED_ORIGINS: "https://payflow.com,https://app.payflow.com"
