apiVersion: v1
kind: Secret
metadata:
  name: payflow-secrets
  labels:
    app.kubernetes.io/name: payflow-api
    app.kubernetes.io/part-of: payflow-platform
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "payflow_production_secure_password"
  SPRING_DATA_REDIS_PASSWORD: ""
  PAYFLOW_SECURITY_JWT_SECRET: "cGF5Zmxvdy1zdXBlci1zZWNyZXQta2V5LWZvci1qd3QtYXV0aGVudGljYXRpb24tdG9rZW4tbWluaW11bS0yNTYtYml0cw=="
