CREATE TABLE users (
    user_id BIGSERIAL PRIMARY KEY,
    reference_id UUID NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    upi_id VARCHAR(100) NOT NULL UNIQUE,
    phone_number VARCHAR(10) NOT NULL,
    balance DECIMAL(19,4) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
